import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { phoneNumber } from "../utils/format";

export default function Home() {
    const [tel, setTel] = useState("(941) 555-0123");
    const [address, setAddress] = useState("185 Berry St");
    const [city, setCity] = useState("Vancouver");
    const [zip, setZip] = useState("V6G 1H2");

    const handlePhoneFormat = (input) => {
        let number = input.target.value;
        let formated = phoneNumber(number);
        setTel(formated);
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <div>
                    <input type='text' />
                    <input type='email' placeholder='janedoe@gmail.com' />
                    <input
                        type='tel'
                        maxlength='16'
                        name=''
                        id=''
                        value={tel}
                        onChange={handlePhoneFormat}
                        autoCorrect='tel'
                        placeholder={tel}
                    />
                    <input
                        class='input'
                        type='text'
                        placeholder={address}
                        required
                        autoCorrect='address-line1'
                    />
                    <input
                        class='input'
                        type='text'
                        placeholder='Vancouver'
                        required
                        autoCorrect='address-level2'
                    ></input>
                </div>
                <div>
                    <input
                        autoCorrect='cc-number'
                        autocorrect='off'
                        spellcheck='false'
                        type='text'
                        name='cardnumber'
                        data-elements-stable-field-name='cardNumber'
                        inputmode='numeric'
                        aria-label='Credit or debit card number'
                        placeholder='Card number'
                        aria-invalid='true'
                        value='4242 4242 4224 242'
                    />
                    <input
                        autoCorrect='cc-exp'
                        autocorrect='off'
                        spellcheck='false'
                        type='text'
                        name='exp-date'
                        data-elements-stable-field-name='cardExpiry'
                        inputmode='numeric'
                        aria-label='Credit or debit card expiration date'
                        placeholder='MM / YY'
                        aria-invalid='false'
                        value=''
                    />
                    <input
                        class='InputElement is-empty Input Input--empty'
                        autoCorrect='postal-code'
                        autocorrect='off'
                        spellcheck='false'
                        type='text'
                        name='postal'
                        data-elements-stable-field-name='postalCode'
                        inputmode='numeric'
                        aria-label='ZIP'
                        placeholder='ZIP'
                        aria-invalid='false'
                        value=''
                    />
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                    target='_blank'
                    rel='noopener noreferrer'
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src='/vercel.svg'
                            alt='Vercel Logo'
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
